GET http://localhost:3001/users

###

POST http://localhost:3001/users
Content-Type: application/json

{
    "userType": "Accountant",
  "firstName": "John",
  "lastName": "Smith",
  "username": "jsmith",
  "password": "123",
  "address": "123 Cherry St",
  "city": "Atlanta",
  "state": "GA",
  "zip": "30060",
  "dob": "1999-12-31",
  "securityAnswer": "Brown"
}